dotenv: .env

dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.3.2"
  - "bugout-dev/dao@0.0.7"
  - "bugout-dev/engine@0.0.3"

compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@moonstream=bugout-dev/dao@0.0.7"
      - "@moonstream-engine=bugout-dev/engine@0.0.3"
