name: Lint game7ctl

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  formatting_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install black
        working-directory: game7ctl/
        run: pip install black
      - name: Black syntax check
        working-directory: game7ctl/
        run: black --check game7ctl
